name: athlete_tracking
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:

  flutter:
    sdk: flutter
  provider: ^6.0.5 
  syncfusion_flutter_charts: ^21.2.3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  google_fonts:
  fl_chart:
  introduction_screen: ^3.1.8
  

  
  web_socket_channel: ^2.1.0
  json_annotation: ^4.3.0
  firebase_core: ^2.10.0
  firebase_database: ^10.1.2
  uuid: ^3.0.7
  cloud_firestore: ^4.5.2
  charts_flutter: ^0.12.0
  sensors: ^2.0.3
  shared_preferences: ^2.1.1
  # google_maps_flutter: ^2.2.8

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Images/assets/icons/Icons8-Ios7-Sports-Running.512.png"
  min_sdk_android: 21 # an


flutter:

  uses-material-design: true

  assets:
    - Images/assets/icons/dumbell.svg
    - Images/assets/icons/apps.svg
    - Images/assets/icons/clock.svg
    - Images/assets/icons/user.svg
    - Images/assets/icons/stats.svg
    - Images/assets/icons/running.svg
    - Images/assets/icons/bike.svg
    - Images/assets/icons/food.svg
    - Images/assets/icons/coffee.svg
    - Images/assets/icons/footprints.svg
    - Images/assets/icons/account.svg
    - Images/assets/icons/heart-beat-3516.svg
    - Images/assets/icons/heart-498.svg
    - Images/assets/icons/black-fast-time-or-deadline-timing-19024.svg
    - Images/assets/icons/map_marker_distance_icon_135422.svg
    - Images/assets/icons/body-mass-index-svgrepo-com.svg
    - Images/assets/icons/total-time-consumption.svg
    - Images/assets/icons/heart-rate-11.svg
    - Images/assets/icons/speed-meter-1.svg
    - Images/assets/icons/speed-6.svg
    - Images/assets/icons/distance-9.svg
    - Images/assets/icons/95ba0f7164f52e5432f401a55e204753.svg
    - Images/assets/icons/calories-svgrepo-com.svg
    - Images/assets/icons/background1.jpg
    - Images/assets/icons/background2.jpg
    - Images/assets/icons/background3.jpg
    - Images/assets/icons/background4.png
    - Images/assets/icons/background5.png
    - Images/assets/icons/hinh1.png
    - Images/assets/icons/hinh2.png
    - Images/assets/icons/hinh3.png
    - Images/assets/icons/hinh4.png
    - Images/assets/icons/hinh5.png
    

   
   
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  # #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
